name: Build and Publish

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Get Git user name
      run: |
        echo "GIT_USER_NAME=$(git config user.name)" >> $GITHUB_ENV

    - name: Get Git user info
      run: |
        echo "GIT_USER_NAME=$(git config user.name)" >> $GITHUB_ENV
        echo "GIT_USER_EMAIL=$(git config user.email)" >> $GITHUB_ENV  
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.
        
    - name: Install setuptools
      run: pip install setuptools
        
    - name: Build wheel file
      run: python setup.py bdist_wheel
      
    - name: Push wheel file to repository
      run: |
        git config user.name "${{ env.GIT_USER_NAME }}"
        git config user.email "${{ env.GIT_USER_EMAIL }}"
        git add dist/*.whl
        git commit -m "Add new wheel file"
        git push