name: Build and Publish

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Get Git user info
      run: |
        GIT_USER_NAME=$(git config --global user.name)
        GIT_USER_EMAIL=$(git config --global user.email)
        echo "GIT_USER_NAME=${GIT_USER_NAME}" >> $GITHUB_ENV
        echo "GIT_USER_EMAIL=${GIT_USER_EMAIL}" >> $GITHUB_ENV  
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        
    - name: Install build package
      run: pip install build
        
    - name: Build wheel file
      run: python -m build
      
    - name: Push wheel file to repository
      run: |
        git config user.name "${{ env.GIT_USER_NAME }}"
        git config user.email "${{ env.GIT_USER_EMAIL }}"
        git add dist/*.whl
        git commit -m "Add new wheel file"
        git push